# cloudbuild.yaml - builds docker image with all required build args
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/oja-local-46990/oja-local/oja-local:latest'
      # Next.js public environment variables
      - '--build-arg'
      - 'NEXT_PUBLIC_API_KEY=${_NEXT_PUBLIC_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_AUTH_DOMAIN=${_NEXT_PUBLIC_AUTH_DOMAIN}'
      - '--build-arg'
      - 'NEXT_PUBLIC_PROJECT_ID=${_NEXT_PUBLIC_PROJECT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_STORAGE_BUCKET=${_NEXT_PUBLIC_STORAGE_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_APP_ID=${_NEXT_PUBLIC_APP_ID}'
      # Server-side environment variables
      - '--build-arg'
      - 'DATABASE_URL=${_DATABASE_URL}'
      - '--build-arg'
      - 'DIRECT_URL=${_DIRECT_URL}'
      - '--build-arg'
      - 'FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL}'
      - '--build-arg'
      - 'FIREBASE_PRIVATE_KEY=${_FIREBASE_PRIVATE_KEY}'
      - '--build-arg'
      - 'GOOGLE_CLOUD_STORAGE_BUCKET=${_GOOGLE_CLOUD_STORAGE_BUCKET}'
      - '.'

images:
  - 'europe-west1-docker.pkg.dev/oja-local-46990/oja-local/oja-local:latest'

options:
  logging: CLOUD_LOGGING_ONLY