steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'europe-west1-docker.pkg.dev/oja-local-469900/marketplace-repo/nextjs:$COMMIT_SHA',
      '.'
    ]

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/oja-local-469900/marketplace-repo/nextjs:$COMMIT_SHA'
    ]

  # (Optional) Step 3: Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/nextjs-app'
      - 'nextjs=europe-west1-docker.pkg.dev/oja-local-469900/marketplace-repo/nextjs:$COMMIT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=europe-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=marketplace-cluster'

images:
  - 'europe-west1-docker.pkg.dev/oja-local-469900/marketplace-repo/nextjs:$COMMIT_SHA'
