steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/oja-local/oja-local:${SHORT_SHA}'
      - '-t'
      - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/oja-local/oja-local:latest'
      # All your existing build args...
      - '--build-arg'
      - 'NEXT_PUBLIC_API_KEY=${_NEXT_PUBLIC_API_KEY}'
      - '--build-arg'
      - 'REDIS_HOST=${_REDIS_HOST}'
      - '--build-arg'
      - 'REDIS_PORT=${_REDIS_PORT}'
      - '--build-arg'
      - 'NEXT_PUBLIC_AUTH_DOMAIN=${_NEXT_PUBLIC_AUTH_DOMAIN}'
      - '--build-arg'
      - 'NEXT_PUBLIC_PROJECT_ID=${_NEXT_PUBLIC_PROJECT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_STORAGE_BUCKET=${_NEXT_PUBLIC_STORAGE_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_APP_ID=${_NEXT_PUBLIC_APP_ID}'
      - '--build-arg'
      - 'DATABASE_URL=${_DATABASE_URL}'
      - '--build-arg'
      - 'DIRECT_URL=${_DIRECT_URL}'
      - '--build-arg'
      - 'FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL}'
      - '--build-arg'
      - 'FIREBASE_PRIVATE_KEY=${_FIREBASE_PRIVATE_KEY}'
      - '--build-arg'
      - 'GOOGLE_CLOUD_STORAGE_BUCKET=${_GOOGLE_CLOUD_STORAGE_BUCKET}'
      - '.'

  # Push both tags
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/oja-local/oja-local:${SHORT_SHA}']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/oja-local/oja-local:latest']

images:
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/oja-local/oja-local:latest'

options:
  logging: CLOUD_LOGGING_ONLY