# cloudbuild.yaml - builds docker image with NEXT_PUBLIC_* build args
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/oja-local-46990/oja-local/oja-local:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_KEY=${_NEXT_PUBLIC_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_AUTH_DOMAIN=${_NEXT_PUBLIC_AUTH_DOMAIN}'
      - '--build-arg'
      - 'NEXT_PUBLIC_PROJECT_ID=${_NEXT_PUBLIC_PROJECT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_STORAGE_BUCKET=${_NEXT_PUBLIC_STORAGE_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_APP_ID=${_NEXT_PUBLIC_APP_ID}'
      - '.'
images:
  - 'europe-west1-docker.pkg.dev/oja-local-46990/oja-local/oja-local:latest'

options:
  logging: CLOUD_LOGGING_ONLY
