apiVersion: apps/v1
kind: Deployment
metadata:
  name: oja-local
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oja-local
  template:
    metadata:
      labels:
        app: oja-local
    spec:
      # It's good practice to use a dedicated service account.
      serviceAccountName: nextjs-app-sa
      containers:
      - name: nextjs
        # TODO: Replace <REGION> and <PROJECT_ID> with your details.
        # It is strongly recommended to use a specific version tag instead of 'latest' for production.
        image: <REGION>-docker.pkg.dev/<PROJECT_ID>/marketplace/nextjs:v1.0.0
        env:
        - name: DB_HOST
          value: "127.0.0.1"
        - name: DB_PORT
          value: "5432"
        # It's best practice to store secrets in a Kubernetes Secret, not directly in the deployment YAML.
        # Create a secret named 'db-credentials' with keys 'user' and 'password'.
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials # The name of your K8s secret
              key: user           # The key in the secret for the username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials # The name of your K8s secret
              key: password       # The key in the secret for the password
        - name: DB_NAME
          value: "marketplace"
        ports:
        - containerPort: 3000
      - name: cloud-sql-proxy
        # Using a specific version is a good practice.
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.0
        args:
          - "--structured-logs"
          - "--port=5432"
          # TODO: Replace <PROJECT_ID> with your actual project ID.
          - "<PROJECT_ID>:us-central1:marketplace-db" # Your Cloud SQL instance connection name
        securityContext:
          runAsNonRoot: true
